theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"

[[block]]
block = "net"
device = "enp34s0"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %H:%M:%S"
